### PR TITLE
feat: show pending config updates due to locked machine

### PR DESCRIPTION
**Pull request by Unix4ever**
Display pending machine config updates count for the `MachineSet` and mark each machine which is locked and has the config update which is not applied yet.

Fixes: https://github.com/siderolabs/omni/issues/15

### CODE REVIEW

**Comment by Unix4ever** [comment]
Screenshot 2024-06-10 at 16 41 21

**Comment by Unix4ever** [comment]
Also fixed the layouts on the small screens a bit.

**Comment by Unix4ever** [comment]
Added CLI output too:
Screenshot 2024-06-10 at 17 01 04

**Comment by smira** [comment]
> Added CLI output too: Screenshot 2024-06-10 at 17 01 04

you even matches colors! :)

**Review by smira — APPROVED** [review]

**Comment by Unix4ever** [comment]
It might look different on some other terminals anyways :)

**Pull request merged**
