### PR TITLE
fix: never remove etcd members which ID is discovered at least once

### PR DESCRIPTION
**Pull request by Unix4ever**
The logic of the etcd audit got outdated with the more recent Talos versions. `apid` now runs in the states where it wasn't available before, so the check for the etcd member might lead to the false-positives.
Also reorder the `auditMember` check sequence to be more correct.

Fixes: https://github.com/siderolabs/omni/issues/750

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
Do we need to run `e2e-upgrades` as well?

**Review by utkuozdemir — APPROVED** [review]
🆒

Will it be compatible wit both older and newer Talos versions?

**Comment by Unix4ever** [comment]
> Will it be compatible wit both older and newer Talos versions?

Yep, it should be.

**Pull request merged**
