### PR TITLE
chore: bump default versions: Talos `1.7.6`, Kubernetes `1.30.5`

### PR DESCRIPTION
**Pull request by utkuozdemir**
Bump them to the latest and greatest versions.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Review by TimJones — APPROVED** [review]
Feels weird that we can't pull those go constants into the typescript frontend :(

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
> Feels weird that we can't pull those go constants into the typescript frontend :(

this TypeScript file is generated from Go actually

**Comment by utkuozdemir** [comment]
> Feels weird that we can't pull those go constants into the typescript frontend :(

Actually the `tsgen:*` instructions above them do exactly that, but statically - we have to run `make generate` after editing the constants.

We could easily change it to fetch dynamically at runtime and/or pick the latest one automatically.

**Comment by smira** [comment]
Should also update https://github.com/siderolabs/omni/blob/c4a4151d7a5d9030ec82fab434932f3d002e59cf/hack/test/integration.sh#L23

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
