### PR TITLE
feat: implement the UI for adjusting machine sets update strategies

### PR DESCRIPTION
**Pull request by Unix4ever**
Allow setting update and delete strategies along with max parallelism.

Fixes: https://github.com/siderolabs/omni/issues/27

### CODE REVIEW

**Comment by Unix4ever** [comment]
https://github.com/siderolabs/omni/assets/830532/e408c9c7-91da-40f0-98e8-10f48c4bc69d

**Comment by rothgar** [comment]
You may want to validate updates to control plane does not cause etcd instability (eg if 3 nodes only allow 1 node rolling). 

For worker nodes a percentage is sometimes better than hard coded rolling because if the cluster scales up (eg 300+ nodes) 5 nodes would still take a long time. IIRC EKS we would allow both settings (hard coded or percentage) and favored the larger one.

**Comment by Unix4ever** [comment]
We don't allow changing this config for control planes, so that's already validated :)
It's always Rolling and 1 node at a time.

**Comment by smira** [comment]
Should the `Unset` be something like "All at the same time" ? idk...

**Review by smira — APPROVED** [review]

**Pull request merged**
