### PR TITLE
feat: implement the UI for configuring extensions during cluster create

### PR DESCRIPTION
**Pull request by Unix4ever**
Fixes: https://github.com/siderolabs/omni/issues/207

The UI allows selecting installed extensions before adding machines to a cluster during cluster creation or scaling.

### CODE REVIEW

**Comment by Unix4ever** [comment]
New UI:

image
image

**Review by utkuozdemir — APPROVED** [review]
Maybe we can enable hello-world-service in the e2e tests on cluster create?

**Comment by Unix4ever** [comment]
> Maybe we can enable hello-world-service in the e2e tests on cluster create?

Well, hello-world-service is already installed there. But we can add qemu-guest-agent there

**Comment by utkuozdemir** [comment]
> > Maybe we can enable hello-world-service in the e2e tests on cluster create?
> 
> Well, hello-world-service is already installed there. But we can add qemu-guest-agent there

ah, right, I mean any small, lightweight extension to get this screen tested.

**Comment by Unix4ever** [comment]
Tested both the modal window and the fact that extension is installed.

**Pull request merged**
