### PR TITLE
chore: do not audit log `GET` requests to k8s

### PR DESCRIPTION
**Pull request by DmitriyMV**
Since we do not audit log read-like requests, I think it makes sense to do the same here.

### CODE REVIEW

**Review by utkuozdemir — APPROVED** [review]

**Comment by smira** [comment]
I don't think we should log the request body, as it might be HUGE, and I don't think that level of details should go to audit logs. The fact that a user X accessed Kubernetes API at time Y for cluster Z is enough. 

API server has its own set of audit logs which provides additional (configurable) details.

**Comment by smira** [comment]
If we don't log the request, we can drop half of the complexity there

**Comment by DmitriyMV** [comment]
@smira 

> If we don't log the request, we can drop half of the complexity there

Done.

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
@Unix4ever we should get it backported I guess

**Pull request merged**
