### PR TITLE
feat: add support bundle download button to cluster overview

### PR DESCRIPTION
**Pull request by utkuozdemir**
Allow downloading support bundles from the UI.
Part of siderolabs/omni#75.

### CODE REVIEW

**Comment by utkuozdemir** [comment]
@Unix4ever not sure if this will be useful at all, but handing this over to you as it is beyond my FE/design skills.

**Comment by Unix4ever** [comment]
Polished the UI, fixed the bug related to the download not being canceled after you close the modal.

Final UI:

https://github.com/user-attachments/assets/1f601a5b-d924-41b2-8593-d6b1b5a948ec

**Review by smira — APPROVED** [review]

**Comment by frezbo** [comment]
> Polished the UI, fixed the bug related to the download not being canceled after you close the modal.
> 
> Final UI:
> Screen.Recording.2024-07-24.at.19.52.00.mov

Cool, can we use nodenames instead of siderolink addresses?

**Comment by Unix4ever** [comment]
> Cool, can we use nodenames instead of siderolink addresses?

Well, that's actually node internal IP, it's just how Talos emulator shows them.
It's how Talos support bundle collector works, so we might need to map it in Omni somehow.

**Pull request merged**
